site_name: Godot 4 Rapid Reference
docs_dir: docs-src
site_dir: docs
nav:
  - "Rapid Reference": index.md
  - Project:
    - "Game Boot": project/game_boot.md
    - "Structure": project/project_structure.md
  - Scene:
    - "Node vs Ref": scene/node_vs_refcounted.md
    - "Visual Elements": scene/scene_visual_elements.md
    - "Scene Manager": scene/scene_manager.md 
  - Class:
    - "Custom": class/custom_classes.md
    - "Instances": class/class_instances.md
    - "Objects": class/objects_and_custom_objects.md
    - "Type Hints": class/typing.md
  - Signal: 
    - "Usage": signals/signal.md
    - "Collision": signals/collision_signals.md
  - Tween:
    - "Tween 2D": tween/tweening_2d.md
    - "Movment Type": tween/movement_types_2d.md
  - UI:
    - "Basics": ui/basic_ui.md
    - "Input": ui/input_events.md
    - "Drag and Drop": ui/drag_and_drop.md
  - Data:
    - "Save/Load": data/save_and_load.md
    - "Working with Data": data/working_with_data.md
  - Resource:
    - "Custom .tres": resource/custom_resources_tres.md
  - Files:
    - "File IO": "files/file_io.md"
    - "Management": "files/file_management.md"
    - "User Files": "files/user_files.md"
  - Modding:
    - "UGC Concepts": modding/ugc_create_and_load.md
    - "System Theory": modding/modding_system_theory.md
  - More:
    - "Groups": more/working_with_groups.md
    - "GraphEdit": more/graph_edit.md
    - "Visual Effects": more/visual_effects.md
    - "Helpers": more/helpers.md
theme:
  name: material
  language: en
  # Path to your site logo (relative to docs_dir)
  logo: images/godot-icon.svg
  # Favicon / site icon (relative to docs_dir)
  favicon: images/godot-icon.svg
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: slate
      primary: blue
      accent: indigo
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.betterem
  - pymdownx.tilde
